config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post 'signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#create'

  resources :captures
  resources :pokemons do
    resources :captures, only: [:new, :index]
  end
  resources :regions
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/capture.rb
class Capture < ApplicationRecord
  belongs_to :user
  belongs_to :pokemon

  validates :pokeball, presence: true

  validates :pokemon, uniqueness: { scope: :user, message: "has already been caught by you" }

  validate :is_valid_catch_date

  scope :order_by_date_captured, -> {order(captured: :desc)}

  private

  def is_valid_catch_date
    if Date.today < captured
      errors.add(:captured, 'Sorry, date captured cannot be in the future.')
    end
  end

end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :region
  belongs_to :user
  has_many :captures
  has_many :users, through: :captures
  accepts_nested_attributes_for :region

  validates :name, presence: true

  validates :name, uniqueness: { scope: :region, message: "has already been added" }

  def self.alphabetically
    order(:name)
  end

  def pokemon_and_region
    "#{name} - #{region.name}"
  end

end

app/models/region.rb
class Region < ApplicationRecord
    has_many :pokemons
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :captures
    has_many :captured_pokemons, through: :captures, source: :pokemon
    has_many :pokemons

    has_secure_password

    validates :username, uniqueness: true, presence: true

    def self.create_by_google(auth)
        self.find_or_create_by(username: auth[:info][:email]) do |u|
          u.password = SecureRandom.hex
        end
    end

    def self.create_by_facebook(auth)
      self.find_or_create_by(username: auth[:info][:email]) do |u|
        u.password = SecureRandom.hex
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    private

    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def redirect_if_not_logged_in
        redirect_to login_path if !logged_in?
    end


end

app/controllers/captures_controller.rb
class CapturesController < ApplicationController
    before_action :redirect_if_not_logged_in

    def new
        if @pokemon = Pokemon.find_by_id(params[:pokemon_id])
            @capture = @pokemon.captures.build
        else
            @capture = Capture.new
        end
    end

    def create
        @capture = current_user.captures.build(capture_params)
        if @capture.save
            redirect_to capture_path(@capture)
        else
            render :new
        end
    end

    def show
        @capture = Capture.find_by_id(params[:id])
    end

    def index
        if @pokemon = Pokemon.find_by_id(params[:pokemon_id])
            @captures = @pokemon.captures
        else
            @captures = current_user.captures.order_by_date_captured
        end
    end

    private

    def capture_params
        params.require(:capture).permit(:pokemon_id, :pokeball, :captured)
    end
    
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
    before_action :set_pokemon, only:[:show, :edit, :update]
    before_action :redirect_if_not_logged_in

    def new
        @pokemon = Pokemon.new
        @pokemon.build_region
    end

    def create
        #@pokemon = Pokemon.new(pokemon_params)
        @pokemon = current_user.pokemons.build(pokemon_params)
        @pokemon.region = Region.find_or_create_by(name: pokemon_params[:region_attributes][:name])
        #@pokemon.user_id = session[:user_id]
        if @pokemon.save
          redirect_to pokemon_path(@pokemon)
        else
          render :new
        end
    end

    def index
        @pokemons = current_user.pokemons.all
    end

    def show
    end

    def edit
    end

    def update
        if @pokemon.update(pokemon_params)
            redirect_to pokemon_path(@pokemon)
        else
            render :edit
        end
    end

    private

    def pokemon_params
        params.require(:pokemon).permit(:name, :description, :region_id, region_attributes: [:name])
    end

    def set_pokemon
        @pokemon = Pokemon.find_by_id(params[:id])
        redirect_to pokemons_path if !@pokemon
     end

end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
    before_action :redirect_if_not_logged_in

    def index
        @regions = Region.all
    end

    def new
        @region = Region.new
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def index
      @pokemon = Pokemon.all.sample
    end

    def new
    end

    def create
        if params[:provider] == 'google_oauth2'
          @user = User.create_by_google(auth)
          session[:user_id] = @user.id
          redirect_to user_path(@user)
        elsif params[:provider] == 'facebook'
          @user = User.create_by_facebook(auth)
          session[:user_id] = @user.id
          redirect_to user_path(@user)
        else
          @user = User.find_by(username: params[:user][:username])
          if @user.try(:authenticate, params[:user][:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
          else
            flash[:error] = "Sorry, login info was incorrect. Please try again."
            redirect_to login_path
          end
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to '/'
    end

    private

    def auth
      request.env['omniauth.auth']
    end
            
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def show
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end

    def create
        @user = User.new(user_params)
    
        if @user.save
          session[:user_id] = @user.id
          redirect_to @user
        else
          render :new
        end
    end
    
    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/captures_helper.rb
module CapturesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/captures/index.html.erb
<% if @pokemon %>
  <h1>Captures for <%= @pokemon.name%> - <%= @pokemon.region.name%></h1>
<% else %>
  <h1>All Captures </h1>
<% end %>


<ul>
<% @captures.each do |c| %>
    <li><%= c.pokemon.name%>: <%= c.pokeball%> - <%= c.captured%></li>
<% end %>
</ul>

app/views/captures/new.html.erb
<h1>Catch a Pokemon </h1>

<%= render partial: 'layouts/errors', locals: {object: @capture}  %>


<%= form_for(@capture) do |f| %>
    <% if params[:pokemon_id] %>
        <%= f.hidden_field :pokemon_id %>
    <% else %>
        <div>
            <%= f.label :pokemon_id, "Select an Pokemon" %>
            <%= f.collection_select :pokemon_id, Pokemon.alphabetically, :id, :pokemon_and_region, include_blank: true %>
        </div>
    <% end %>
    <div>
        <%= f.label :pokeball %>
        <%= f.text_field :pokeball %>
    </div>
    <div>
        <%= f.label :captured %>
        <%= f.date_field :captured %>
    </div>

    <%= f.submit "Add Catch" %>

<% end%>

app/views/captures/show.html.erb
<h1><%= @capture.pokeball%> - <%= @capture.captured%> </h1>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPokemon2Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div>
    <% if logged_in? %>
      <%= link_to "Home", current_user %>
      <%= link_to "Add Pokemon", new_pokemon_path %>
      <%= link_to "All Pokemon", pokemons_path %>
      <%= link_to "Add a Capture", new_capture_path %>
      <%= link_to "All Captures", captures_path %>
      <%= link_to "All Regions", regions_path %>
      <%= link_to "Log Out", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Login", login_path %> |
      <%= link_to "Signup", signup_path %> |
      <%= link_to "Sign in with Google", "/auth/google_oauth2" %> |
      <%= link_to "Sign in with Facebook", "/auth/facebook" %>
    <% end %>
  </div>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/edit.html.erb
<h1>Edit your Pokemon</h1>

<%= render partial: 'layouts/errors', locals: {object: @pokemon}  %>

<%= form_for(@pokemon) do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_field :description %>
    </div>
    
    <%= f.submit "Update Pokemon" %>
<% end %>

app/views/pokemons/index.html.erb
<h1>Pokemon</h1>

<ul>
<% @pokemons.each do |p| %>
    <li><%= p.name%> (<%= p.region.name%>) - <%= p.description%></li>
<% end %>
</ul>

app/views/pokemons/new.html.erb
<h1>Add a Pokemon to your collection!</h1>

<%= render partial: 'layouts/errors', locals: {object: @pokemon}  %>

<%= form_for(@pokemon) do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_field :description %>
    </div>
    
    <p> Add a Region </p>
    <div>
        <%=f.fields_for :region do |r| %>
            <%= r.label :region %>
            <%= r.text_field :name %>
        <% end %>
    </div>

    <%= f.submit "Add Pokemon" %>
<% end %>

app/views/pokemons/show.html.erb
<h1><%= @pokemon.name%> (<%= @pokemon.region.name %>) </h1>

<div>
  <p><%= @pokemon.description %></p>
</div>


<%= link_to "Edit #{@pokemon.name}", edit_pokemon_path(@pokemon) if @pokemon.user == current_user%>

app/views/regions/index.html.erb
<h1>All Regions</h1>

<ol>
  <% @regions.each do |region| %>
    <li><%= region.name%></li>
  <% end %>
</ol>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= render partial: 'layouts/errors', locals: {object: @user}  %>

<%= form_for(@user) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
Welcome Trainer <%= @user.username%>!

<h3>Here are the Pokemon you've caught:</h3>
<div>
  <% @user.captured_pokemons.each do |f|%>
    <p><%= link_to "#{f.name}", pokemon_path(f) %> - <%= f.region.name %></p>
  <% end %>
</div>